version: '3'
services:
  master:
    build:
      context: .
      dockerfile: dockerfile_master
    ports:
      - "5000:5000"
    depends_on:
      - secondary1
      - secondary2

  secondary1:
    build:
      context: .
      dockerfile: dockerfile_secondary
    ports:
      - "5001:5001"

  secondary2:
    build:
      context: .
      dockerfile: dockerfile_secondary
    ports:
      - "5002:5001"





