FROM python:3.12-slim

WORKDIR /app
COPY . /app

RUN apt-get update && apt-get install -y curl && \
    pip install flask==3.1.0 aiohttp==3.11.8 requests==2.32.3

EXPOSE 5000

CMD ["python", "master.py"] 