version: '3'
services:
  master:
    build:
      context: .
      dockerfile: dockerfile_master
    ports:
      - "5000:5000"
    depends_on:
      - secondary1
      - secondary2
    networks:
      - replicated_log_network

  secondary1:
    build:
      context: .
      dockerfile: dockerfile_secondary
    ports:
      - "5001:5001"
    networks:
      - replicated_log_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 3

  secondary2:
    build:
      context: .
      dockerfile: dockerfile_secondary
    ports:
      - "5002:5001"
    networks:
      - replicated_log_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 3
    
networks:
  replicated_log_network:
    driver: bridge





